NDefines.NBuildings.MAX_SHARED_SLOTS = 35
NDefines.NFocus.FOCUS_POINT_DAYS = 1 -- Each point takes one day
NDefines.NFocus.MAX_SAVED_FOCUS_PROGRESS = 15 -- This much progress can be saved while not having a focus selected
NDefines.NGame.START_DATE = "1999.4.1.12"
NDefines.NGame.END_DATE = "2023.1.28.23"
NDefines.NGame.LAG_DAYS_FOR_LOWER_SPEED = 10
NDefines.NGame.LAG_DAYS_FOR_PAUSE = 25
NDefines.NMilitary.CORPS_COMMANDER_DIVISIONS_CAP = 32
NDefines.NMilitary.FIELD_MARSHAL_DIVISIONS_CAP = 32
NDefines_CareerProfile.NCareerProfile.MOD_STATISTICS_GROUP_NAME = "Genshin Impact: the Twist of Teyvat"
NDefines.NCountry.MIN_STABILITY = -1.0
NDefines.NCountry.MIN_WAR_SUPPORT = -1.0
NDefines.NDiplomacy.TENSION_CAPITULATE = 0.0						-- Scale of the amount of tension created by a countries capitulation.