NDefines.NBuildings.MAX_SHARED_SLOTS = 35
NDefines.NFocus.FOCUS_POINT_DAYS = 1 -- Each point takes one day
NDefines.NFocus.MAX_SAVED_FOCUS_PROGRESS = 15 -- This much progress can be saved while not having a focus selected
NDefines.NGame.START_DATE = "1999.4.1.12"
NDefines.NGame.END_DATE = "2023.1.28.23"
NDefines.NGame.LAG_DAYS_FOR_LOWER_SPEED = 10
NDefines.NGame.LAG_DAYS_FOR_PAUSE = 25
NDefines.NMilitary.CORPS_COMMANDER_DIVISIONS_CAP = 32
NDefines.NMilitary.FIELD_MARSHAL_DIVISIONS_CAP = 32
NDefines.NSupply.NODE_INITIAL_SUPPLY_FLOW = 4.0
NDefines.NSupply.NODE_ADDED_PENALTY_PER_PROVINCE = 1.0
NDefines.NSupply.SUPPLY_FLOW_DROP_REDUCTION_AT_MAX_INFRA = 0.50
NDefines.NSupply.RAILWAY_FLOW_PER_LEVEL = 10
NDefines.NSupply.NODE_FLOW_BONUS_PER_RAIL_LEVEL = 0.5
NDefines_CareerProfile.NCareerProfile.MOD_STATISTICS_GROUP_NAME = "Genshin Impact: the Twist of Teyvat"